### PR TITLE
Email, date and url fields are validated

### PR DESCRIPTION
**Pull request by Sundraiz-Shah**

### CODE REVIEW

**Comment by Aidajafarbigloo** [comment]
@Sundraiz-Shah, thank you for the updates. After testing the UI, I observed the following issues:

- When editing URLs and attempting to download the JSON, after an error alert is triggered, the page displays the message: `An unexpected error occurred: cannot unpack non-iterable NoneType object`.
- The error alert occurs even if the URL fields are left empty, which seems incorrect since these fields are not mandatory, and users should be able to leave them blank.
- If the user changes the URL to `https://gitlab.com/zdin-zle/zle-platform/repository/me`, it still passes validation despite returning a 404 error. This could be problematic as the URL is not actually valid unless we want to check only the format and not its accessibility.
- Regarding parsing the names, some email addresses still contain numbers after extraction.
- `Email validation` in the Contributor table does not work, either after extraction or editing an existing email address.

**Comment by Sundraiz-Shah** [comment]
@Aidajafarbigloo According to your feedback I fixed those issues which you highlight. 
1) Now you will not see this message "An unexpected error occurred: cannot unpack non-iterable NoneType object" after clicking download json button
2) For URL fields it will check the pattern of URLs and gives error if URL pattern will be wrong otherwise empty fields will not give an error.
3) I tried to solve it from front end but it will be solved from backend so i would suggest to open another issue for this point.
4) Email can contains numbers but i tried to fix the regix . 
5) in contribution table it validate the email after editing.

**Comment by Aidajafarbigloo** [comment]
@Sundraiz-Shah Thank you for the changes.
After testing, here is my opinion:
- When trying to download the JSON, with having 1 or more URL fields incorrect, the user currently receives two alerts and needs to press the download button twice in case of invalid input.
  User faces, for example, `The URL in the optional field "url-" is incorrect.` and `The URL in the optional field "url-" is incorrect.`
  I think it might be more user-friendly to consolidate all errors into a single alert.
 - Regarding the alert message, I think we can remove the `-` from that (`The URL in the optional field "codeRepository-" is incorrect.`).
 - As we are on the validation process, I think a check on the dates: `dateModified` and `dateCreated` could be helpful. (e.g., dateCreated cannot be set to some day in the future or cannot be later than dateModified, plus similar scenarios)
 - In both contributors' and authors' table, an empty row can be added, which we need to avoid.

**Comment by Sundraiz-Shah** [comment]
@Aidajafarbigloo Please check and review the code. I fixed all the issues which you mentioned before.

**Comment by Sundraiz-Shah** [comment]
@Aidajafarbigloo After discussion date validation with you. I fix the issue. Now json will not download if the date is not validate. Please review it and let me know if you found any other issue.

**Comment by Aidajafarbigloo** [comment]
@Sundraiz-Shah Thank you for the updates.
Could you please fix a bug in the style? When correcting fields containing URLs after downloading, they still remain highlighted in pink.

**Pull request merged**
